apiVersion: v1
kind: ConfigMap
metadata:
  name: streamer-config
data:
  WIDTH: "1280"
  HEIGHT: "720"
  RECEIVER_IP: "video-receiver-transcoder"
  RECEIVER_PORT: "5554"
  USE_D435I: "true"
  USE_H264: "true"
  BITRATE: "4000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: receiver-config
data:
  WIDTH: "1920"
  HEIGHT: "1080"
  SRT_IP: "mediamtx"
  SRT_PORT: "8890"
  SPEED_PRESET: "ultrafast"
  STREAM_NAME: "go1_camera"
  ENABLE_MONITORING: "true"
  USE_H264: "true"
  BITRATE: "10000"